// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7nvR2YOYWN0J_foCV4FtKuIUnPKSMpFk',
    appId: '1:961092907782:web:2ca44ddd114258fa10e487',
    messagingSenderId: '961092907782',
    projectId: 'wallabie-chat',
    authDomain: 'wallabie-chat.firebaseapp.com',
    storageBucket: 'wallabie-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzCZH0Hdg5WFP8kesxsMWGRNUBRQ1RcU',
    appId: '1:961092907782:android:102d26dac461312410e487',
    messagingSenderId: '961092907782',
    projectId: 'wallabie-chat',
    storageBucket: 'wallabie-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSenKkoi8J6OIQtKLM5oSPUGwRHhBVukU',
    appId: '1:961092907782:ios:d457e46aa4908ae610e487',
    messagingSenderId: '961092907782',
    projectId: 'wallabie-chat',
    storageBucket: 'wallabie-chat.firebasestorage.app',
    iosBundleId: 'com.example.augustChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSenKkoi8J6OIQtKLM5oSPUGwRHhBVukU',
    appId: '1:961092907782:ios:d457e46aa4908ae610e487',
    messagingSenderId: '961092907782',
    projectId: 'wallabie-chat',
    storageBucket: 'wallabie-chat.firebasestorage.app',
    iosBundleId: 'com.example.augustChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7nvR2YOYWN0J_foCV4FtKuIUnPKSMpFk',
    appId: '1:961092907782:web:e62a4748da8751a610e487',
    messagingSenderId: '961092907782',
    projectId: 'wallabie-chat',
    authDomain: 'wallabie-chat.firebaseapp.com',
    storageBucket: 'wallabie-chat.firebasestorage.app',
  );

}